---
- name: ensure ssh is installed
  apt: pkg=openssh-server state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  notify:
    - restart ssh

- name: ensure ufw is installed
  apt: pkg=ufw state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  notify:
    - restart ufw

- name: ensure fail2ban is installed
  apt: pkg=fail2ban state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  notify:
    - restart fail2ban

- name: ensure ssh is configured
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
    - restart ssh

- name: ensure ufw is configured
  template: src=ufw_config.j2 dest=/etc/default/ufw owner=root group=root mode=0644
  register: ufw_ipv6

- name: ensure ufw always allows ssh
  ufw: rule=allow port=ssh proto=tcp

- name: ensure ufw is disabled when ipv6 is changed
  ufw: state=disabled
  when: ufw_ipv6.changed

- name: ensure ufw is enabled, disabled or reset
  ufw: state={{ security_ufw_state }}
  register: ufw_state

- name: ensure ufw is configured
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }} state=reloaded
  with_items: security_ufw_ports
  when: '"enabled" in ufw_state.invocation.module_args'

- name: ensure fail2ban is installed
  apt: pkg=fail2ban state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  notify:
    - restart fail2ban

- name: ensure ssh, ufw and fail2ban starts on a fresh reboot
  service: name={{ item }} state=started enabled=yes
  with_items:
    - ssh
    - ufw
    - fail2ban